[package]
name = "r-bindgen"
version = "0.1.0"
authors = ["Tim Süberkrüb <dev@timsueberkrueb.io>"]
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
proc-quote = "0.3"

[lib]
proc-macro = true
